export const CRM_VNEXT_OPERATOR_CAPABILITIES_SCHEMA_VERSION =
  "crm-vnext-operator-capabilities-2026-05-11" as const;

export type CrmVNextOperatorCapabilityEndpoint = {
  id: string;
  method: "GET" | "POST";
  path: string;
  purpose: string;
  readOnly: boolean;
  returnsPersonRows: boolean;
  writesFiles: false | "only_with_commit";
  mutatesRecords: false | "only_with_commit";
  outbound: false;
  preferredNextStep: string;
  notes: string[];
};

export type CrmVNextOperatorBrowserRoute = {
  id: string;
  path: string;
  purpose: string;
  audience: Array<"alejandro" | "mantis" | "team_later">;
  readOnly: true;
  outbound: false;
};

export type CrmVNextOperatorLocalCommand = {
  id: string;
  command: string;
  purpose: string;
  defaultMode: "dry_run" | "preview";
  writesFiles: "never" | "only_with_explicit_flag";
  outbound: false;
  notes: string[];
};

export type CrmVNextOperatorGuardrail = {
  code: string;
  severity: "hard_stop" | "human_approval_required";
  description: string;
};

export type CrmVNextOperatorEscalationTrigger = {
  code: string;
  alertAlejandro: true;
  description: string;
  exactUnblockActionNeeded: string;
};

export type CrmVNextOperatorRecommendedFlowStep = {
  step: number;
  id: string;
  action: string;
  use: string;
  stopCondition: string | null;
};

export type CrmVNextOperatorCapabilities = {
  schemaVersion: typeof CRM_VNEXT_OPERATOR_CAPABILITIES_SCHEMA_VERSION;
  generatedAt: string;
  mode: "read_only_operator_capabilities";
  operatingModel: {
    dayToDayOperator: "Mantis via OpenClaw";
    builderRole: "repository contracts, code, docs, and local verification";
    humanDecisionOwner: "Alejandro";
  };
  recommendedFlow: CrmVNextOperatorRecommendedFlowStep[];
  apiEndpoints: CrmVNextOperatorCapabilityEndpoint[];
  browserRoutes: CrmVNextOperatorBrowserRoute[];
  localCommands: CrmVNextOperatorLocalCommand[];
  guardrails: CrmVNextOperatorGuardrail[];
  escalationTriggers: CrmVNextOperatorEscalationTrigger[];
  safety: {
    outboundProhibited: true;
    recordMutationRequiresExplicitApproval: true;
    credentialMutationProhibited: true;
    manyChatLiveMutationProhibited: true;
    instagramPermissionMutationProhibited: true;
    mailerLiteCredentialMutationProhibited: true;
  };
};

const apiEndpoints: CrmVNextOperatorCapabilityEndpoint[] = [
  {
    id: "operator_capabilities",
    method: "GET",
    path: "/api/crm-vnext/operator-capabilities",
    purpose: "Stable map of safe CRM vNext surfaces for Mantis/OpenClaw.",
    readOnly: true,
    returnsPersonRows: false,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use this first when the operator needs to know what CRM vNext can safely expose.",
    notes: [
      "Does not read person-card artifacts.",
      "Does not include local filesystem paths.",
    ],
  },
  {
    id: "readiness",
    method: "GET",
    path: "/api/crm-vnext/readiness",
    purpose: "Local readiness check for source availability, queue contracts, and safety posture.",
    readOnly: true,
    returnsPersonRows: false,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Run before daily, queue, or decision brief jobs when Mantis needs an operational green light.",
    notes: [
      "Does not return person rows.",
      "Prefers the local vNext card store when present; falls back to legacy Person Cards V1.",
      "Local paths are redacted even when the source is unavailable.",
    ],
  },
  {
    id: "source_ledger",
    method: "GET",
    path: "/api/crm-vnext/source-ledger",
    purpose: "Read-only source map for local CRM artifacts, freshness, gaps, and safe ingestion planning.",
    readOnly: true,
    returnsPersonRows: false,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use before choosing MailerLite, Instagram, Telegram, or human-report ingestion work.",
    notes: ["Does not call external APIs.", "Does not expose local filesystem paths."],
  },
  {
    id: "fact_intake",
    method: "POST",
    path: "/api/crm-vnext/fact-intake",
    purpose: "Dry-run parser for turning conversational reports into auditable CRM facts.",
    readOnly: true,
    returnsPersonRows: false,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use to preview how Alejandro/Juana/Mantis reports would become facts before any write path exists.",
    notes: ["Dry-run only.", "No person cards are mutated.", "Ambiguous identities remain reviewable."],
  },
  {
    id: "fact_store",
    method: "POST",
    path: "/api/crm-vnext/fact-store",
    purpose: "Local append/read surface for approved CRM facts.",
    readOnly: true,
    returnsPersonRows: false,
    writesFiles: "only_with_commit",
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use only after fact intake preview; person cards remain unchanged.",
    notes: [
      "POST commit writes only to the local fact ledger.",
      "GET reads stored facts and summary.",
      "Requires approvedBy for committed writes.",
      "Does not mutate person cards.",
    ],
  },
  {
    id: "activation_run",
    method: "POST",
    path: "/api/crm-vnext/activation-run",
    purpose: "Run one safe batch through fact intake, optional fact-store append, identity review, and card diff.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: "only_with_commit",
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use for the first real activation batch from Alejandro/Juana/Mantis reports.",
    notes: [
      "Default mode is dry-run.",
      "Commit writes only approved facts to the local Fact Store.",
      "No person cards are mutated.",
      "No external APIs or outbound channels are called.",
    ],
  },
  {
    id: "identity_stitching_research",
    method: "POST",
    path: "/api/crm-vnext/identity-stitching-research",
    purpose: "Read-only identity candidate research from fact clues, local person cards, and local MailerLite bridge exports.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use when Activation Run produces unmatched or name-only clues before asking Alejandro for identifiers.",
    notes: [
      "Prefers the local vNext person-card store when present; falls back to legacy Person Cards V1 only when forced.",
      "Does not call live MailerLite APIs.",
      "Does not mutate person cards or Fact Store.",
      "Restricted service context is flagged for human review.",
      "Weak name matches are evidence only, never automatic stitching approval.",
    ],
  },
  {
    id: "gmail_evidence_helper",
    method: "POST",
    path: "/api/crm-vnext/gmail-evidence-helper",
    purpose: "Read-only Gmail evidence planner and packet builder for identity stitching.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use when Gmail may contain identity or service evidence before Deep Local Stitching.",
    notes: [
      "Builds Gmail query plans from fact clues.",
      "Converts supplied Gmail search results into redacted evidenceSources packets.",
      "The API does not call live Gmail and does not read credentials.",
      "If the local Gmail connector is blocked, return the auth blocker instead of refreshing credentials inside CRM.",
    ],
  },
  {
    id: "contacts_evidence_helper",
    method: "POST",
    path: "/api/crm-vnext/contacts-evidence-helper",
    purpose: "Read-only Contacts evidence planner and packet builder for identity/contact-field stitching.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use when macOS Contacts or a contacts export may contain missing phone, email, or handle fields.",
    notes: [
      "Builds contacts search terms from fact clues.",
      "Converts supplied Contacts results into contacts_app_export evidenceSources.",
      "The API does not read macOS Contacts directly and does not mutate contacts.",
      "The local CLI can query the macOS Contacts SQLite store read-only when Alejandro has granted permission.",
      "If Contacts permission is blocked, return an auth blocker instead of attempting UI or credential work.",
    ],
  },
  {
    id: "mailerlite_evidence_helper",
    method: "POST",
    path: "/api/crm-vnext/mailerlite-evidence-helper",
    purpose: "Read-only MailerLite evidence planner and packet builder for identity/contact-field stitching.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use when MailerLite may contain missing email, phone, location, groups, or subscriber status.",
    notes: [
      "Builds MailerLite subscriber search terms from fact clues.",
      "Converts supplied subscriber results into mailerlite_export evidenceSources.",
      "The API does not call live MailerLite and does not read credentials.",
      "The local CLI can use the existing read-only MailerLite CLI route; if it returns 401, report the blocker instead of printing or rotating credentials.",
      "Never create, update, tag, group, delete, or suppress subscribers from this flow.",
    ],
  },
  {
    id: "google_drive_evidence_helper",
    method: "POST",
    path: "/api/crm-vnext/google-drive-evidence-helper",
    purpose: "Read-only Google Drive/Docs/Sheets evidence planner and packet builder for identity, retreat, and contact-field stitching.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use when Google Drive tables or docs may contain retreat attendance, family context, email, phone, or program interest evidence.",
    notes: [
      "Builds Drive/Docs/Sheets search terms from fact clues.",
      "Converts supplied read-only Drive/Sheets results into google_drive_export or retreat_table evidenceSources.",
      "The API does not call live Google Drive and does not read credentials.",
      "Family or companion email ambiguity is flagged for review before assigning a primary email.",
      "Never create, edit, move, share, or delete Drive files from this flow.",
    ],
  },
  {
    id: "lead_capture_evidence_helper",
    method: "POST",
    path: "/api/crm-vnext/lead-capture-evidence-helper",
    purpose: "Read-only ManyChat/CRM webhook/Vercel/WhatsApp lead-capture evidence planner and packet builder.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use when an Instagram-origin contact should have email/phone evidence in onboarding, webhook, proxy, or class-delivery traces.",
    notes: [
      "Builds ManyChat, CRM webhook, Vercel proxy, WhatsApp automation, and MailerLite follow-up search suggestions from fact clues.",
      "Converts supplied read-only capture results into lead_capture_export evidenceSources.",
      "The API does not call live ManyChat, Instagram, MailerLite, WhatsApp, or Vercel and does not read credentials.",
      "Never edit, pause, resume, or test ManyChat LIVE from this flow.",
      "Use for Eliana-style cases where an Instagram handle should connect to email/phone captured earlier.",
    ],
  },
  {
    id: "deep_local_stitching",
    method: "POST",
    path: "/api/crm-vnext/deep-local-stitching",
    purpose: "Read-only deep local evidence search before creating new cards or asking Alejandro for missing context.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use when identity research would create a new card but Alejandro expects more local evidence.",
    notes: [
      "Searches configured local memory files by default.",
      "Can include local CSVs, retreat tables, downloads, and contact exports with includeExpandedSources.",
      "Can ingest supplied Gmail/contact/MailerLite/Google Drive evidence packets through evidenceSources without giving the CRM live connector credentials.",
      "Extracts review-only identity signals such as full-name candidates, emails, phones, and handles from evidence hits.",
      "Summarizes present and missing contact fields so Mantis knows whether email/phone still require hunting.",
      "Preserves source diversity so repeated memory hits do not hide useful contact, Zoom, Gmail, or table evidence.",
      "Does not expose absolute filesystem paths.",
      "Does not mutate person cards or Fact Store.",
      "Defers new-card creation when local evidence exists.",
      "Gmail, MailerLite, Google Drive, and live contacts app searches should be performed by Mantis/Codex as read-only external investigation, then supplied as evidence packets.",
    ],
  },
  {
    id: "multi_service_card_proposal",
    method: "POST",
    path: "/api/crm-vnext/multi-service-card-proposal",
    purpose: "Read-only card proposal that preserves multiple service relationships on one contact.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use after identity stitching research to prepare a reviewed card create/merge/enrichment proposal.",
    notes: [
      "Prefers the local vNext person-card store when present; falls back to legacy Person Cards V1 only when forced.",
      "Does not write person cards or Fact Store.",
      "Preserves yoga, retreats, therapy, mentorship, digital products, and community events as parallel relationships.",
      "Restricted service context is flagged and cannot drive outbound without review.",
      "All operations are proposal-only until Alejandro approves a card-write policy.",
    ],
  },
  {
    id: "card_write_merge_policy",
    method: "POST",
    path: "/api/crm-vnext/card-write-merge-policy",
    purpose: "Read-only policy decision for create, enrich, merge, defer, or ask-more-identity card actions.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use after multi-service proposal and evidence review before any future card-write implementation.",
    notes: [
      "Prefers the local vNext person-card store when present; falls back to legacy Person Cards V1 only when forced.",
      "Does not mutate person cards or Fact Store.",
      "Encodes that automatic writes and automatic merges remain prohibited.",
      "Accepts Gmail/contact evidence packets and consults local MailerLite bridge rows.",
      "Recognizes Mantis Chrome/Gmail read-only search as a viable alternate evidence route.",
      "Recommends MailerLite read-only consultation before final card creation or merge when email/tags matter.",
      "Adds a contact-field hunt next step when identity is enriched but email or phone remains missing.",
    ],
  },
  {
    id: "card_apply_preview",
    method: "POST",
    path: "/api/crm-vnext/card-apply-preview",
    purpose: "Read-only preview of exact hypothetical card operations with executed=false.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use after card write/merge policy to inspect the exact operations that a future approved apply command would need.",
    notes: [
      "Prefers the local vNext person-card store when present; falls back to legacy Person Cards V1 only when forced.",
      "Does not mutate person cards or Fact Store.",
      "Does not implement a write command.",
      "Can show fuller identity candidates from evidence in proposed drafts while keeping them review-only.",
      "Consumes the local evidence-review decisions ledger when supplied, so confirmed/unassigned email decisions shape the preview.",
      "Reports missing contact fields separately from service/context evidence.",
      "Every operation is marked executed=false and wouldMutate=true.",
      "Blocked previews list the required approvals before any future apply path can exist.",
    ],
  },
  {
    id: "evidence_review_packet",
    method: "POST",
    path: "/api/crm-vnext/evidence-review-packet",
    purpose: "Read-only decision packet for ambiguous evidence such as family/shared email ownership.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use after Card Apply Preview when an email, identity, or family/companion clue needs explicit human confirmation.",
    notes: [
      "Turns preview evidence into explicit questions and options for Alejandro or Mantis.",
      "Keeps ambiguous emails visible as candidates without assigning them as primary emails.",
      "Suppresses questions already resolved in the evidence-review decisions ledger when supplied.",
      "Can suggest related-person candidates when a family/companion name appears near an ambiguous email.",
      "Does not mutate cards, write Fact Store, call live APIs, or send outbound messages.",
      "A selected option is not an apply approval; future writes still need card-write policy approval.",
    ],
  },
  {
    id: "evidence_review_decisions",
    method: "POST",
    path: "/api/crm-vnext/evidence-review-decisions",
    purpose: "Local read/append ledger for approved evidence-review decisions, without mutating cards.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: "only_with_commit",
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use after Alejandro confirms an evidence-review option so future write paths have explicit provenance.",
    notes: [
      "GET reads the local evidence decision ledger.",
      "POST previews by default and writes only with commit=true plus approvedBy.",
      "Stores decisions such as keep family email unassigned or confirm email for subject.",
      "Does not mutate person cards, write Fact Store, call live APIs, or send outbound messages.",
      "A stored decision is provenance for a future write path, not the write itself.",
    ],
  },
  {
    id: "evidence_approval_workbench",
    method: "POST",
    path: "/api/crm-vnext/evidence-approval-workbench",
    purpose: "Read-only queue of unresolved evidence decisions with recommended defaults for Mantis/Alejandro.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use before applying evidence decisions when Mantis needs one compact queue of questions.",
    notes: [
      "Builds a review queue from Evidence Review Packet and Card Write Approval Packet.",
      "Shows recommended decision CLI fragments for each candidate email.",
      "Suppresses questions already resolved in the evidence-review decision ledger.",
      "Does not store decisions, mutate cards, write Fact Store, call live APIs, or send outbound messages.",
    ],
  },
  {
    id: "evidence_approval_application",
    method: "POST",
    path: "/api/crm-vnext/evidence-approval-application",
    purpose: "Apply approved evidence decisions to the local decision ledger and rerun approval packets before card writes.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: "only_with_commit",
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use after Alejandro confirms evidence ownership so Mantis can see which items become approval-ready.",
    notes: [
      "Dry-run by default; commit writes only to the evidence-review decision ledger.",
      "Shows before/after approval packet summaries and resolved evidence questions.",
      "Does not mutate person cards, write Fact Store, call live APIs, or send outbound messages.",
      "Even after application, card writes still need a separate card-write approval path.",
    ],
  },
  {
    id: "stitch_batch_review",
    method: "POST",
    path: "/api/crm-vnext/stitch-batch-review",
    purpose: "Read-only batch review that ranks multiple create/enrich/merge/defer stitching candidates.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use when Mantis wants one approval-oriented view of several contacts before any card write.",
    notes: [
      "Combines Card Apply Preview, Evidence Review Packet, and stored evidence decisions.",
      "Shows open questions, proposed identity fields, services, blockers, and safe next step per contact.",
      "Does not mutate cards, write Fact Store, call live APIs, or send outbound messages.",
      "A batch item marked approval-ready still needs a separate human card-write approval.",
    ],
  },
  {
    id: "card_write_approval_packet",
    method: "POST",
    path: "/api/crm-vnext/card-write-approval-packet",
    purpose: "Read-only human approval packet before any future card-write path.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use after Stitch Batch Review when a contact has no open evidence questions and needs explicit write approval.",
    notes: [
      "Prefers the local vNext person-card store when present; falls back to legacy Person Cards V1 only when forced.",
      "Separates approval-ready items from evidence-blocked or identity-blocked items.",
      "Lists the exact approval scopes: card write policy, identity match, merge policy, restricted service context, and no-outbound boundary.",
      "Does not mutate cards, write Fact Store, call live APIs, or send outbound messages.",
      "Approval here prepares a future reviewed write path; it still executes zero operations.",
      "Does not re-ask ownership for an email already assigned on the existing vNext card.",
    ],
  },
  {
    id: "batch_operating_loop",
    method: "POST",
    path: "/api/crm-vnext/batch-operating-loop",
    purpose: "Read-only operating loop that routes a batch into evidence questions, blocked identity work, ready approvals, and dry-run write preview.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use when Mantis needs one natural-language batch command instead of manually chaining all approval layers.",
    notes: [
      "Combines Evidence Approval Workbench, Card Write Approval Packet, and Card Write Apply dry-run.",
      "For natural Mantis requests, first follow docs/crm-vnext/mantis-natural-batch-protocol.md to produce contact-keyed evidence JSON.",
      "Creates a blocked identity queue with recommended read-only search lanes and copy-ready prompts for Mantis.",
      "Reads the local vNext card store when present; falls back to legacy Person Cards V1.",
      "Does not mutate cards, write Fact Store, call live APIs, send outbound messages, or touch credentials.",
    ],
  },
  {
    id: "engagement_signal_preview",
    method: "POST",
    path: "/api/crm-vnext/engagement-signal-preview",
    purpose: "Read-only preview of how supplied MailerLite, Gmail, Instagram, or manual engagement signals would affect CRM warmth scores and review queues.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use after card identity is stable and Mantis has supplied read-only engagement exports or snapshots.",
    notes: [
      "Accepts supplied engagement signals only; the API does not call live MailerLite, Gmail, Instagram, ManyChat, Drive, or Contacts.",
      "Returns before/after scoring deltas, new reason/risk codes, and internal recommended queues.",
      "Does not mutate cards, write Fact Store, send outbound messages, or touch credentials.",
      "A warmed score is not permission to contact someone; it only prioritizes internal review.",
    ],
  },
  {
    id: "card_write_apply",
    method: "POST",
    path: "/api/crm-vnext/card-write-apply",
    purpose: "Guarded local write path from approval-ready items into the CRM vNext card store.",
    readOnly: false,
    returnsPersonRows: true,
    writesFiles: "only_with_commit",
    mutatesRecords: "only_with_commit",
    outbound: false,
    preferredNextStep: "Use only after Card Write Approval Packet when Alejandro has explicitly approved the selected item(s).",
    notes: [
      "Dry-run by default.",
      "Commit requires approvedBy plus explicit approvalItemIds or applyAllReady=true.",
      "Creates local backups before writing the vNext card store.",
      "Writes only local vNext card-store and card-write ledger files.",
      "Stages merge-review items; it does not merge records automatically.",
      "Does not write Fact Store, call live APIs, send outbound messages, or touch credentials.",
    ],
  },
  {
    id: "card_merge_review_resolver",
    method: "POST",
    path: "/api/crm-vnext/card-merge-review-resolver",
    purpose: "Guarded local resolver for merge-review queue items staged by Card Write Apply.",
    readOnly: false,
    returnsPersonRows: true,
    writesFiles: "only_with_commit",
    mutatesRecords: "only_with_commit",
    outbound: false,
    preferredNextStep: "Use only after a staged merge has been inspected and Alejandro approves the selected review id.",
    notes: [
      "Dry-run by default.",
      "Commit requires approvedBy plus explicit reviewIds or resolveAllReady=true.",
      "Can consume supplied read-only evidenceSources before resolving, such as MailerLite subscriber packets from Mantis.",
      "Restricted service context also requires ackRestrictedService=true.",
      "Creates backups before writing the vNext card store.",
      "Writes only local vNext card-store and merge-review ledger files.",
      "Does not write Fact Store, call live APIs, send outbound messages, or touch credentials.",
    ],
  },
  {
    id: "identity_review",
    method: "GET",
    path: "/api/crm-vnext/identity-review",
    purpose: "Read-only review queue that matches stored facts to local person cards and previews card rebuilds.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use after storing approved facts to separate ready previews from identity or business-review blockers.",
    notes: [
      "No person cards are mutated.",
      "Local source paths are redacted from API output.",
      "Name-only matches remain review items until a stable identity is confirmed.",
    ],
  },
  {
    id: "card_rebuild_diff",
    method: "GET",
    path: "/api/crm-vnext/card-rebuild-diff",
    purpose: "Read-only diff of how ready facts would change local person cards.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use after identity review to inspect proposed card changes before any write policy exists.",
    notes: [
      "No person cards are written.",
      "Blocked facts remain visible but are excluded from diffs.",
      "This is the sprint-close review surface before future card mutation decisions.",
    ],
  },
  {
    id: "community_insights",
    method: "GET",
    path: "/api/crm-vnext/community-insights",
    purpose: "Aggregate community metrics, lifecycle distribution, identity gaps, and top priority signals.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use for broad dashboard-level diagnostics before drilling into queues.",
    notes: [
      "Internal only.",
      "Prefers the local vNext card store when present; falls back to legacy Person Cards V1.",
      "Bounded person rows may appear in top-priority sections.",
    ],
  },
  {
    id: "community_queues",
    method: "GET",
    path: "/api/crm-vnext/community-queues",
    purpose: "Queue counts, status totals, and snapshot metadata for recurring operator monitoring.",
    readOnly: true,
    returnsPersonRows: false,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "If status is watch or notify, inspect the matching queue brief.",
    notes: [
      "Safe for frequent local monitor checks.",
      "Prefers the local vNext card store when present; falls back to legacy Person Cards V1.",
      "The API does not write snapshots.",
    ],
  },
  {
    id: "community_queue_brief",
    method: "GET",
    path: "/api/crm-vnext/community-queue-brief?queueId=<queueId>&limit=<n>",
    purpose: "Bounded person-level brief for one Mantis queue.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use person-card for exact detail on one selected person before drafting a decision note.",
    notes: [
      "Keep limits small.",
      "Prefers the local vNext card store when present; falls back to legacy Person Cards V1.",
      "Planning signal only; no permission to contact anyone.",
    ],
  },
  {
    id: "community_decision_brief",
    method: "GET",
    path: "/api/crm-vnext/community-decision-brief?queueId=<queueId>&limit=<n>",
    purpose: "Internal approval-boundary brief for one queue before any human or outbound decision.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use when a queue requires Alejandro's decision or a clear no-send approval boundary.",
    notes: [
      "Bounded candidates only.",
      "Prefers the local vNext card store when present; falls back to legacy Person Cards V1.",
      "No delivery, no outreach, no CRM mutation.",
    ],
  },
  {
    id: "community_daily_brief",
    method: "GET",
    path: "/api/crm-vnext/community-daily-brief",
    purpose: "Compact daily operating brief with community totals, queue status, highlights, and safe next steps.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Use this as the first daily CRM read.",
    notes: [
      "Focus queues are bounded.",
      "Prefers the local vNext card store when present; falls back to legacy Person Cards V1.",
      "Notify-level queues require human decision before outbound action.",
    ],
  },
  {
    id: "person_card",
    method: "GET",
    path: "/api/crm-vnext/person-card?personId=<personId>",
    purpose: "Exact vNext person-card read for one stable person id.",
    readOnly: true,
    returnsPersonRows: true,
    writesFiles: false,
    mutatesRecords: false,
    outbound: false,
    preferredNextStep: "Prepare an internal decision note if the card suggests human review or commercial follow-up.",
    notes: [
      "Exact lookup only.",
      "Prefers the local vNext card store when present; falls back to legacy Person Cards V1.",
      "nextAction is a planning signal, not send approval.",
    ],
  },
];

const browserRoutes: CrmVNextOperatorBrowserRoute[] = [
  {
    id: "dashboard",
    path: "/crm-vnext",
    purpose: "Main local dashboard for community intelligence.",
    audience: ["alejandro", "mantis", "team_later"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "daily_brief",
    path: "/crm-vnext/daily-brief",
    purpose: "Readable daily operating brief mirroring the daily brief API.",
    audience: ["alejandro", "mantis"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "queues",
    path: "/crm-vnext/queues",
    purpose: "Saved Mantis queue views.",
    audience: ["alejandro", "mantis"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "people_explorer",
    path: "/crm-vnext/people",
    purpose: "Filterable local search over vNext person cards.",
    audience: ["alejandro", "mantis", "team_later"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "source_ledger",
    path: "/crm-vnext/sources",
    purpose: "Browser view for source freshness, coverage gaps, and ingestion readiness.",
    audience: ["alejandro", "mantis"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "fact_intake_lab",
    path: "/crm-vnext/fact-intake",
    purpose: "Dry-run lab for conversational CRM facts before write-path approval.",
    audience: ["alejandro", "mantis", "team_later"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "fact_store",
    path: "/crm-vnext/fact-store",
    purpose: "Local view of stored CRM facts and card-apply readiness.",
    audience: ["alejandro", "mantis", "team_later"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "activation_run",
    path: "/crm-vnext/activation-run",
    purpose: "Dry-run one real fact batch through the whole local CRM vNext activation pipeline.",
    audience: ["alejandro", "mantis", "team_later"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "identity_stitching_research",
    path: "/crm-vnext/identity-stitching-research",
    purpose: "Read-only candidate research for unmatched names, handles, and service clues.",
    audience: ["alejandro", "mantis", "team_later"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "deep_local_stitching",
    path: "/crm-vnext/deep-local-stitching",
    purpose: "Read-only local evidence search before new-card creation.",
    audience: ["alejandro", "mantis", "team_later"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "multi_service_card_proposal",
    path: "/crm-vnext/multi-service-card-proposal",
    purpose: "Proposal view for multi-service person-card creation, merge, and enrichment review.",
    audience: ["alejandro", "mantis", "team_later"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "evidence_approval_workbench",
    path: "/crm-vnext/evidence-approval-workbench",
    purpose: "Browser review queue for unresolved evidence ownership decisions.",
    audience: ["alejandro", "mantis", "team_later"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "identity_review",
    path: "/crm-vnext/identity-review",
    purpose: "Review stored facts against local person cards before any future rebuild.",
    audience: ["alejandro", "mantis", "team_later"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "card_rebuild_diff",
    path: "/crm-vnext/card-rebuild-diff",
    purpose: "Read-only before/after diff for ready fact-to-card rebuild proposals.",
    audience: ["alejandro", "mantis", "team_later"],
    readOnly: true,
    outbound: false,
  },
  {
    id: "person_detail",
    path: "/crm-vnext/person/[personId]",
    purpose: "Exact browser view for one vNext person card.",
    audience: ["alejandro", "mantis", "team_later"],
    readOnly: true,
    outbound: false,
  },
];

const localCommands: CrmVNextOperatorLocalCommand[] = [
  {
    id: "source_ledger",
    command: "npm run crm:vnext:source-ledger",
    purpose: "Read local source freshness and coverage gaps through the source-ledger API.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Use --expected-mailerlite-contacts when Alejandro has a known MailerLite floor.",
      "This command never reads credentials or calls external APIs.",
    ],
  },
  {
    id: "fact_intake_preview",
    command: "npm run crm:vnext:fact-intake -- --text <text>",
    purpose: "Preview how a human or source report would become CRM facts.",
    defaultMode: "dry_run",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Default output is a structured draft only.",
      "No CRM record is mutated and no message is sent.",
    ],
  },
  {
    id: "fact_store",
    command: "npm run crm:vnext:fact-store",
    purpose: "List stored CRM facts or append approved facts to the local fact ledger.",
    defaultMode: "dry_run",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Default with --text previews an append.",
      "Use --write --approved-by <name> to commit locally.",
      "This command never mutates person cards.",
    ],
  },
  {
    id: "activation_run",
    command: "npm run crm:vnext:activation-run -- --text <text>",
    purpose: "Run a fact batch through intake, store preview/write, identity review, and card diff.",
    defaultMode: "dry_run",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Default run previews the pipeline without storing facts.",
      "Use --write --approved-by <name> to commit approved facts locally.",
      "This command never mutates person cards.",
    ],
  },
  {
    id: "identity_stitching_research",
    command: "npm run crm:vnext:identity-stitching-research -- --text <text>",
    purpose: "Research identity candidates from local person cards and local MailerLite bridge exports.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Read-only candidate search.",
      "Does not call live MailerLite or external APIs.",
      "Use --fail-on-decision when an automation should stop on human-review recommendations.",
    ],
  },
  {
    id: "gmail_evidence_helper",
    command: "npm run crm:vnext:gmail-evidence -- --text <text>",
    purpose: "Plan Gmail searches and convert read-only Gmail results into stitching evidence packets.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Default mode only plans queries and converts supplied results.",
      "Use --search-results-file to pass connector/export results into CRM as redacted evidenceSources.",
      "Optional --use-gog runs read-only local Gmail searches; if OAuth is blocked, it reports the blocker.",
      "This command never sends email, mutates Gmail, mutates person cards, or writes Fact Store.",
    ],
  },
  {
    id: "contacts_evidence_helper",
    command: "npm run crm:vnext:contacts-evidence -- --use-macos-contacts-db --text <text>",
    purpose: "Plan and collect read-only Contacts evidence for missing phone, email, or handle fields.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Default mode only plans queries and converts supplied results.",
      "Use --use-macos-contacts-db only after Alejandro has granted Contacts read permission.",
      "This command never mutates Contacts, cards, Fact Store, or outbound channels.",
      "No credentials or .env files are read.",
    ],
  },
  {
    id: "mailerlite_evidence_helper",
    command: "npm run crm:vnext:mailerlite-evidence -- --text <text>",
    purpose: "Plan and collect read-only MailerLite evidence for missing email, phone, location, groups, or subscriber status.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Default mode only plans queries and converts supplied subscriber results.",
      "Use --search-results-file to pass Mantis/OpenClaw/API/export results into CRM as mailerlite_export evidenceSources.",
      "Optional --use-mailerlite-cli runs the existing local MailerLite CLI read-only; if auth is blocked, it reports 401 without printing credentials.",
      "This command never mutates MailerLite subscribers, groups, tags, automations, cards, Fact Store, or outbound channels.",
    ],
  },
  {
    id: "google_drive_evidence_helper",
    command: "npm run crm:vnext:google-drive-evidence -- --text <text>",
    purpose: "Plan and convert read-only Google Drive/Docs/Sheets rows into identity and retreat evidence packets.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Default mode only plans queries and converts supplied Drive/Sheets results.",
      "Use --search-results-file to pass Mantis/OpenClaw Google Drive connector results into CRM.",
      "Flags family or companion email ambiguity before any primary email assignment.",
      "This command never edits Drive files, mutates cards, writes Fact Store, or sends outbound messages.",
    ],
  },
  {
    id: "lead_capture_evidence_helper",
    command: "npm run crm:vnext:lead-capture-evidence -- --text <text>",
    purpose: "Plan and convert read-only ManyChat/CRM webhook/Vercel/WhatsApp lead-capture traces into identity evidence packets.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Default mode only plans searches and converts supplied capture results.",
      "Use --search-results-file to pass Mantis/OpenClaw exports or selected webhook/proxy rows into CRM.",
      "This command never edits ManyChat LIVE, calls Instagram, mutates MailerLite, mutates cards, writes Fact Store, or sends outbound messages.",
      "Use before accepting new-card creation for Instagram-origin people whose email/phone should exist in capture traces.",
    ],
  },
  {
    id: "instagram_dm_ui_evidence",
    command: "npm run crm:vnext:instagram-dm-ui-evidence -- --observations-file <json>",
    purpose: "Convert read-only Instagram DM UI search observations into email-to-handle bridge evidence packets.",
    defaultMode: "preview",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Use when a known email or phone found in CRM/MailerLite/proxy evidence can be searched in Instagram Messages UI.",
      "This command does not open Instagram or call live APIs; it converts supplied human/Mantis UI observations into instagram_dm_ui_export evidenceSources.",
      "When city/country appear as self-location phrases in the thread, pass city/country plus a short locationText/locationEvidence phrase; do not treat event locations as the person's city.",
      "No send, like, react, follow, unfollow, permission, credential, ManyChat LIVE, card, or Fact Store mutation is allowed.",
      "Feed the resulting evidenceSources into Deep Local Stitching, Card Apply Preview, or a later approval packet.",
    ],
  },
  {
    id: "ig_origin_batch_prompt",
    command: "npm run crm:vnext:ig-origin-batch-prompt -- --latest-writes <n> --limit <n>",
    purpose: "Prepare a copy-ready Mantis prompt for Instagram/onboarding batches with compact DM thread-context instructions.",
    defaultMode: "preview",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Reads only the local vNext card store and card-write ledger.",
      "Prioritizes likely Instagram/onboarding contacts with missing handle, phone, city, country, or low context.",
      "Prompts Mantis to capture city/country from explicit DM self-location clues while keeping retreat/event locations as context only.",
      "Use --markdown-out to save a copy-ready prompt for the CRM Telegram group with Mantis.",
      "This command does not inspect Instagram, call live APIs, mutate cards, write Fact Store, touch credentials, or send outbound.",
    ],
  },
  {
    id: "context_fact_proposals",
    command: "npm run crm:vnext:context-fact-proposals -- --evidence-file <json>",
    purpose: "Convert rich Mantis evidenceSources into reviewed context/fact promotion proposals before any card evidence write.",
    defaultMode: "preview",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Reads supplied evidenceSources plus the local vNext card store.",
      "Separates promote_to_card_evidence items from identity gaps, weak collisions, and sensitive review-only context.",
      "Use --markdown-out to create a human review sheet for Alejandro/Mantis.",
      "This command never mutates cards, writes Fact Store, calls live APIs, touches credentials, or sends outbound.",
    ],
  },
  {
    id: "context_fact_apply",
    command: "npm run crm:vnext:context-fact-apply -- --proposal-file <json> --proposal-id <id>",
    purpose: "Append explicitly approved context/fact proposals to existing local card evidence with backup and ledger.",
    defaultMode: "dry_run",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Dry-run by default.",
      "Committed writes require --write, --approved-by, and explicit --proposal-id values or --apply-all-ready.",
      "Writes only local card evidence plus a local context-fact ledger after backup.",
      "Never creates cards, mutates identity/scoring/product/channel fields, writes Fact Store, calls live APIs, touches credentials, or sends outbound.",
    ],
  },
  {
    id: "deep_local_stitching",
    command: "npm run crm:vnext:deep-local-stitching -- --include-expanded-sources --evidence-file <json> --text <text>",
    purpose: "Search configured local evidence sources before creating a new card.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Read-only local evidence search.",
      "Use --include-expanded-sources to include local CSVs, retreat tables, downloads, and contact exports.",
      "Use --evidence-file for Gmail/contact/MailerLite/Google Drive evidence packets gathered by a read-only connector or export.",
      "No live APIs, no credentials, no outbound.",
      "Use --fail-on-deferred when an automation should stop if local evidence defers new-card creation.",
    ],
  },
  {
    id: "multi_service_card_proposal",
    command: "npm run crm:vnext:multi-service-card-proposal -- --text <text>",
    purpose: "Build a proposal-only card target with all service relationships preserved together.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Read-only proposal builder.",
      "Prefers the local vNext person-card store when present.",
      "Does not mutate person cards or Fact Store.",
      "Use --fail-on-approval when an automation should stop on identity or privacy approvals.",
    ],
  },
  {
    id: "card_write_merge_policy",
    command: "npm run crm:vnext:card-write-merge-policy -- --include-expanded-sources --evidence-file <json> --text <text>",
    purpose: "Evaluate whether card work should create, enrich, merge, defer, or ask for more identity.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Read-only policy evaluator.",
      "Uses the local vNext card store when present, plus local MailerLite bridge rows, local evidence, and supplied evidence packets.",
      "Documents Gmail browser and MailerLite read-only consultation rules for Mantis.",
      "This command never mutates cards, writes Fact Store, sends outbound, or calls live Gmail/MailerLite APIs.",
    ],
  },
  {
    id: "card_apply_preview",
    command: "npm run crm:vnext:card-apply-preview -- --include-expanded-sources --evidence-file <json> --text <text>",
    purpose: "Render exact hypothetical card operations from the policy layer without applying them.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Read-only operation preview.",
      "Prefers the local vNext person-card store when present.",
      "Uses review-only identity signals from evidence to enrich proposed drafts when the clue was sparse.",
      "Pass --decision-ledger-path when Mantis should apply already-approved evidence decisions.",
      "Every operation has executed=false.",
      "This command never mutates cards, merges records, writes Fact Store, or sends outbound.",
      "Use --fail-on-blocked when automation should stop if any preview still needs review.",
    ],
  },
  {
    id: "evidence_review_packet",
    command: "npm run crm:vnext:evidence-review-packet -- --include-expanded-sources --evidence-file <json> --text <text>",
    purpose: "Prepare focused human decision questions for ambiguous evidence before any card write.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Read-only approval packet builder.",
      "Use after card-apply-preview when candidate emails or family/companion evidence need ownership confirmation.",
      "Pass --decision-ledger-path to avoid asking again about already-approved evidence decisions.",
      "For Mayerli/Ariana-style rows, the recommended default is to keep the email unassigned until confirmed.",
      "This command never mutates cards, writes Fact Store, sends outbound, or calls live Gmail/Drive/MailerLite APIs.",
      "Use --fail-on-open-review when automation should stop if ownership questions remain open.",
    ],
  },
  {
    id: "evidence_review_decisions",
    command: "npm run crm:vnext:evidence-review-decisions -- --packet-file <json> --select-email <email=option>",
    purpose: "Preview or commit approved evidence-review decisions to a local ledger.",
    defaultMode: "preview",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Preview by default.",
      "Use --write --approved-by <name> only after Alejandro confirms the decision.",
      "Use --select-email email=keep_email_unassigned_family_or_companion for family/shared email cases.",
      "This command never mutates cards, writes Fact Store, sends outbound, or calls live APIs.",
    ],
  },
  {
    id: "evidence_approval_workbench",
    command: "npm run crm:vnext:evidence-approval-workbench -- --include-expanded-sources --evidence-file <json> --decision-ledger-path <jsonl> --text <text>",
    purpose: "Prepare one compact queue of evidence ownership questions and recommended decision defaults.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Use when several contacts have open email ownership questions.",
      "Outputs --select-email fragments that can be passed to evidence-approval-application after Alejandro confirms.",
      "This command never stores decisions, mutates cards, writes Fact Store, sends outbound, or calls live APIs.",
    ],
  },
  {
    id: "evidence_approval_application",
    command: "npm run crm:vnext:evidence-approval-application -- --include-expanded-sources --evidence-file <json> --decision-ledger-path <jsonl> --text <text> --select-email <email=option>",
    purpose: "Preview or commit evidence decisions and immediately rerun the card-write approval packet.",
    defaultMode: "dry_run",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Use after Alejandro confirms email ownership or family/companion status.",
      "Preview shows before/after open questions and newly ready approval items.",
      "Use --write --approved-by <name> only after explicit confirmation.",
      "This command writes only to the evidence-review decision ledger; it never mutates cards, Fact Store, live APIs, or outbound channels.",
    ],
  },
  {
    id: "stitch_batch_review",
    command: "npm run crm:vnext:stitch-batch-review -- --include-expanded-sources --evidence-file <json> --decision-ledger-path <jsonl> --text <text>",
    purpose: "Summarize multiple stitching candidates in one approval-oriented batch.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Read-only batch reviewer.",
      "Combines preview operations, unresolved evidence questions, and stored decisions.",
      "Use before asking Alejandro to approve several create/enrich/merge/defer recommendations.",
      "This command never mutates cards, writes Fact Store, sends outbound, or calls live APIs.",
      "Use --fail-on-open-review when automation should stop if any evidence questions remain open.",
    ],
  },
  {
    id: "card_write_approval_packet",
    command: "npm run crm:vnext:card-write-approval-packet -- --include-expanded-sources --evidence-file <json> --decision-ledger-path <jsonl> --text <text>",
    purpose: "Prepare explicit human approval packets for future card writes without executing them.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Read-only approval packet builder.",
      "Prefers the local vNext person-card store when present.",
      "Use --connected-evidence-only when a curated evidence packet should skip default local memory search.",
      "Use after stitch-batch-review when at least one item has no open evidence questions.",
      "Shows approval scopes and checklist per contact.",
      "This command never mutates cards, writes Fact Store, sends outbound, or calls live APIs.",
      "Use --fail-on-blocked when automation should stop if any approval item is blocked.",
    ],
  },
  {
    id: "batch_operating_loop",
    command: "npm run crm:vnext:batch-operating-loop -- --include-expanded-sources --evidence-file <json> --decision-ledger-path <jsonl> --text <text>",
    purpose: "Run one read-only batch loop for Mantis: evidence questions, blocked identity queue, ready approvals, and dry-run write preview.",
    defaultMode: "preview",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Default mode writes nothing; --out may save the compact local report.",
      "Use when Alejandro says natural things like 'probemos un batch nuevo'.",
      "If Mantis is doing the hunt, ask her to follow docs/crm-vnext/mantis-natural-batch-protocol.md and save contact-keyed JSON under Documents/Mantis-Reports.",
      "Returns operator prompts for blocked identity cases so Mantis can search Contacts, MailerLite, Gmail, Drive, lead-capture traces, and exports read-only.",
      "This command never mutates cards, writes Fact Store, sends outbound, calls live APIs, or touches credentials.",
      "Use --fail-on-open-work when automation should stop if evidence or identity queues remain open.",
    ],
  },
  {
    id: "engagement_signal_preview",
    command: "npm run crm:vnext:engagement-signal-preview -- --signals-file <json>",
    purpose: "Preview how read-only MailerLite/Gmail/Instagram/manual engagement snapshots would move CRM warmth scores and internal queues.",
    defaultMode: "preview",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Default mode writes nothing; --out may save the compact local report.",
      "Use when Mantis has already gathered engagement evidence read-only from MailerLite, Gmail replies, IG traces, or manual snapshots.",
      "This command never mutates cards, writes Fact Store, sends outbound, calls live APIs, or touches credentials.",
      "Use --fail-on-unmatched when automation should stop if any engagement signal lacks a matching card.",
    ],
  },
  {
    id: "human_enrichment_questions",
    command: "npm run crm:vnext:human-enrichment-questions -- --batch-loop-file <json> --person-id <personId> | --latest-writes <n>",
    purpose: "Generate person-by-person prompts so Alejandro can add remembered context after a batch.",
    defaultMode: "preview",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Default run prints a read-only summary; --out and --markdown-out may save local question packets.",
      "Use after a Mantis batch loop, card apply, or any moment where Alejandro says he knows more about a contact.",
      "After approved local writes, use --latest-writes to seed questions from the card-write ledger without manually copying person IDs.",
      "Answers should go through Fact Intake or a later approved card-write batch; this command itself never mutates cards.",
      "This command never calls live APIs, touches credentials, writes Fact Store, or sends outbound.",
    ],
  },
  {
    id: "card_write_apply",
    command: "npm run crm:vnext:card-write-apply -- --include-expanded-sources --evidence-file <json> --decision-ledger-path <jsonl> --text <text>",
    purpose: "Preview or commit selected approval-ready items into the local CRM vNext card store.",
    defaultMode: "dry_run",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Dry-run by default.",
      "Use --write --approved-by <name> plus --approval-item-id <id> or --apply-all-ready after explicit approval.",
      "Creates backups before committed local writes.",
      "Writes only the local vNext card store and card-write ledger.",
      "Does not merge records automatically, write Fact Store, call live APIs, send outbound, or touch credentials.",
    ],
  },
  {
    id: "card_merge_review_resolver",
    command: "npm run crm:vnext:card-merge-review-resolver -- --review-id <reviewId>",
    purpose: "Preview or commit selected staged merge-review items into the local CRM vNext card store.",
    defaultMode: "dry_run",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Dry-run by default.",
      "Use --write --approved-by <name> plus --review-id <id> or --resolve-all-ready after explicit approval.",
      "Use --evidence-file <json> when Mantis has read-only MailerLite/Gmail/Drive/contact evidence that should fill missing fields before resolving.",
      "Use --ack-restricted-service when the merge includes therapy or other restricted service context.",
      "Creates backups before committed local merge resolutions.",
      "Writes only the local vNext card store and merge-review ledger.",
      "Does not write Fact Store, call live APIs, send outbound, or touch credentials.",
    ],
  },
  {
    id: "identity_review",
    command: "npm run crm:vnext:identity-review",
    purpose: "Read stored facts and preview which local cards could be rebuilt after identity review.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Read-only review queue.",
      "Use --fail-on-review when an automation should stop on unmatched or review-required facts.",
      "This command never mutates person cards.",
    ],
  },
  {
    id: "card_rebuild_diff",
    command: "npm run crm:vnext:card-rebuild-diff",
    purpose: "Preview read-only card changes generated from ready identity-review facts.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Shows proposed operations only.",
      "Use --fail-on-blocked when an automation should stop on unresolved review items.",
      "This command never mutates person cards.",
    ],
  },
  {
    id: "readiness_preflight",
    command: "npm run crm:vnext:readiness",
    purpose: "Run a local readiness preflight before CRM vNext operator jobs.",
    defaultMode: "preview",
    writesFiles: "never",
    outbound: false,
    notes: [
      "Returns source counts, queue totals, readiness checks, and next operator action.",
      "Use --fail-on-blocked or --fail-on-watch when a job should stop on degraded readiness.",
      "This command never sends Telegram, Instagram, email, WhatsApp, or ManyChat.",
    ],
  },
  {
    id: "queue_monitor",
    command: "npm run crm:vnext:queue-monitor",
    purpose: "Read queue status through the local API and optionally persist snapshot or local alert payload files.",
    defaultMode: "dry_run",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Default run does not write files.",
      "Use explicit write flags for local snapshot or alert-payload artifacts.",
      "This command never sends Telegram, Instagram, email, or WhatsApp.",
    ],
  },
  {
    id: "daily_brief_export",
    command: "npm run crm:vnext:daily-brief",
    purpose: "Render the daily brief to stdout or local Markdown/JSON files for handoff.",
    defaultMode: "preview",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Default run previews Markdown only.",
      "Use explicit write flags for local Markdown/JSON files.",
      "This command never delivers the brief to external channels.",
    ],
  },
  {
    id: "decision_brief_export",
    command: "npm run crm:vnext:decision-brief -- --queue-id <queueId>",
    purpose: "Render one queue decision brief to stdout or local Markdown/JSON files for internal approval notes.",
    defaultMode: "preview",
    writesFiles: "only_with_explicit_flag",
    outbound: false,
    notes: [
      "Default run previews metadata and a short Markdown header.",
      "Use explicit write flags for local Markdown/JSON files.",
      "This command never sends the decision brief to Telegram, Instagram, email, WhatsApp, or ManyChat.",
    ],
  },
];

const guardrails: CrmVNextOperatorGuardrail[] = [
  {
    code: "do_not_touch_manychat_live",
    severity: "hard_stop",
    description: "Do not edit, pause, replace, or test against the live ManyChat flow without explicit approval.",
  },
  {
    code: "do_not_touch_instagram_credentials_or_permissions",
    severity: "hard_stop",
    description: "Do not refresh tokens, request permissions, or change Instagram API configuration without approval.",
  },
  {
    code: "do_not_touch_mailerlite_credentials",
    severity: "hard_stop",
    description: "Do not read, rotate, or modify MailerLite credentials in this phase.",
  },
  {
    code: "no_outbound_channels",
    severity: "human_approval_required",
    description: "Do not send Telegram, Instagram, WhatsApp, email, or public messages from CRM vNext unless approved.",
  },
  {
    code: "no_record_mutation",
    severity: "human_approval_required",
    description: "Do not mutate CRM records outside explicit approved local write lanes with backup and provenance.",
  },
];

const escalationTriggers: CrmVNextOperatorEscalationTrigger[] = [
  {
    code: "external_channel_approval",
    alertAlejandro: true,
    description: "Any proposed Telegram, Instagram, WhatsApp, email, or ManyChat send/delivery needs approval first.",
    exactUnblockActionNeeded: "Ask Alejandro to approve the specific channel, audience, copy, and one-run scope.",
  },
  {
    code: "credential_or_permission_refresh",
    alertAlejandro: true,
    description: "Any API auth, credential, Keychain, OAuth, or platform permission prompt is a human unblock.",
    exactUnblockActionNeeded: "Ask Alejandro to authorize the exact credential or permission in person.",
  },
  {
    code: "notify_queue_present",
    alertAlejandro: true,
    description: "A notify-level CRM queue means the system should prepare a decision brief instead of taking action.",
    exactUnblockActionNeeded: "Ask Alejandro to decide the follow-up strategy before any outbound move.",
  },
  {
    code: "source_data_contract_break",
    alertAlejandro: true,
    description: "If the local person-card artifact shape changes and APIs cannot read it, development is blocked.",
    exactUnblockActionNeeded: "Ask Alejandro whether to repair the local artifact adapter or switch source priority.",
  },
];

export const buildCrmVNextOperatorCapabilities = (
  options: { now?: string | Date } = {},
): CrmVNextOperatorCapabilities => {
  const generatedAt =
    options.now instanceof Date
      ? options.now.toISOString()
      : options.now || new Date().toISOString();

  return {
    schemaVersion: CRM_VNEXT_OPERATOR_CAPABILITIES_SCHEMA_VERSION,
    generatedAt,
    mode: "read_only_operator_capabilities",
    operatingModel: {
      dayToDayOperator: "Mantis via OpenClaw",
      builderRole: "repository contracts, code, docs, and local verification",
      humanDecisionOwner: "Alejandro",
    },
    recommendedFlow: [
      {
        step: 1,
        id: "read_capabilities",
        action: "Confirm the current safe CRM vNext surfaces.",
        use: "/api/crm-vnext/operator-capabilities",
        stopCondition: null,
      },
      {
        step: 2,
        id: "read_readiness",
        action: "Confirm local source and operator contracts are usable.",
        use: "/api/crm-vnext/readiness",
        stopCondition: "If status is blocked, repair the local source before running briefs.",
      },
      {
        step: 3,
        id: "read_source_ledger",
        action: "Check which sources are fresh, stale, blocked, or coverage-limited.",
        use: "/api/crm-vnext/source-ledger",
        stopCondition: "If the next step needs credentials or live APIs, stop and request approval.",
      },
      {
        step: 4,
        id: "preview_fact_intake",
        action: "When Alejandro/Juana/Mantis reports a community fact, preview the fact draft first.",
        use: "/api/crm-vnext/fact-intake",
        stopCondition: "Do not persist the fact until a reviewed write path exists.",
      },
      {
        step: 5,
        id: "store_approved_facts",
        action: "Store approved facts in the local fact ledger when the intake draft is acceptable.",
        use: "/api/crm-vnext/fact-store",
        stopCondition: "Do not rebuild or mutate person cards from stored facts yet.",
      },
      {
        step: 6,
        id: "activation_run",
        action: "Run a reviewed fact batch through the full local activation pipeline.",
        use: "/api/crm-vnext/activation-run",
        stopCondition: "Default to dry-run; commit only approved real facts to the local Fact Store.",
      },
      {
        step: 7,
        id: "identity_stitching_research",
        action: "When a batch has unmatched or name-only people, research local identity candidates before asking Alejandro.",
        use: "/api/crm-vnext/identity-stitching-research",
        stopCondition: "Do not merge or create cards automatically; return evidence and confidence only.",
      },
      {
        step: 8,
        id: "gmail_evidence_helper",
        action: "When Gmail may hold identity or service proof, plan safe searches and convert supplied results into evidence packets.",
        use: "/api/crm-vnext/gmail-evidence-helper",
        stopCondition: "If Gmail auth is blocked, report the blocker; do not refresh credentials inside CRM.",
      },
      {
        step: 9,
        id: "contacts_evidence_helper",
        action: "When Contacts may hold missing phone, email, or handle fields, collect read-only contacts_app_export packets.",
        use: "/api/crm-vnext/contacts-evidence-helper",
        stopCondition: "If Contacts permission is blocked, ask Alejandro to grant local read access; do not mutate Contacts.",
      },
      {
        step: 10,
        id: "mailerlite_evidence_helper",
        action: "When MailerLite may hold subscriber identity, contact, group, or engagement proof, collect read-only mailerlite_export packets.",
        use: "/api/crm-vnext/mailerlite-evidence-helper",
        stopCondition: "If MailerLite auth is blocked, ask for connector refresh or let Mantis supply results; never rotate or print credentials inside CRM.",
      },
      {
        step: 11,
        id: "google_drive_evidence_helper",
        action: "When Drive/Docs/Sheets may hold retreat tables or program interest rows, collect read-only google_drive_export or retreat_table packets.",
        use: "/api/crm-vnext/google-drive-evidence-helper",
        stopCondition: "If a row email may belong to a family member or companion, keep it review-only before assigning it to the subject.",
      },
      {
        step: 12,
        id: "lead_capture_evidence_helper",
        action: "When Instagram-origin contacts should have captured email/phone evidence, collect read-only lead_capture_export packets from ManyChat/webhook/proxy/WhatsApp traces.",
        use: "/api/crm-vnext/lead-capture-evidence-helper",
        stopCondition: "If live ManyChat, Instagram, MailerLite, WhatsApp, or credential access is needed, stop and ask for explicit approval.",
      },
      {
        step: 13,
        id: "deep_local_stitching",
        action: "If a new-card candidate appears, search local and connected evidence sources before accepting creation.",
        use: "/api/crm-vnext/deep-local-stitching",
        stopCondition: "If local evidence exists, defer card creation and prepare a review packet.",
      },
      {
        step: 14,
        id: "multi_service_card_proposal",
        action: "Convert identity research plus service facts into a proposal that preserves parallel service relationships.",
        use: "/api/crm-vnext/multi-service-card-proposal",
        stopCondition: "Do not apply proposed operations until Alejandro approves identity, privacy, and card-write policy.",
      },
      {
        step: 15,
        id: "card_write_merge_policy",
        action: "Decide whether the proposal should create, enrich, merge, defer, or ask for more identity.",
        use: "/api/crm-vnext/card-write-merge-policy",
        stopCondition: "Automatic writes and merges remain prohibited; this only prepares the approval boundary.",
      },
      {
        step: 16,
        id: "card_apply_preview",
        action: "Preview the exact hypothetical card operations without executing them.",
        use: "/api/crm-vnext/card-apply-preview",
        stopCondition: "Do not treat preview operations as approval to mutate cards.",
      },
      {
        step: 17,
        id: "evidence_review_packet",
        action: "If preview contains ambiguous evidence, prepare focused ownership/identity questions before any write.",
        use: "/api/crm-vnext/evidence-review-packet",
        stopCondition: "If an email may belong to a family member or companion, keep it unassigned until Alejandro confirms ownership.",
      },
      {
        step: 18,
        id: "evidence_approval_workbench",
        action: "Bundle unresolved evidence questions into one decision queue with recommended defaults.",
        use: "/api/crm-vnext/evidence-approval-workbench",
        stopCondition: "Do not store decisions from recommended defaults until Alejandro confirms them.",
      },
      {
        step: 19,
        id: "evidence_review_decisions",
        action: "When Alejandro confirms a review option, append the decision to the local approval ledger.",
        use: "/api/crm-vnext/evidence-review-decisions",
        stopCondition: "Ledger append is not a card write; future writes still require explicit card-write approval.",
      },
      {
        step: 20,
        id: "evidence_approval_application",
        action: "Apply approved evidence decisions and rerun the approval packet to see what becomes ready.",
        use: "/api/crm-vnext/evidence-approval-application",
        stopCondition: "This may write only the local decision ledger with commit; it still does not mutate person cards.",
      },
      {
        step: 21,
        id: "batch_operating_loop",
        action: "Run one standard batch loop; for natural Mantis requests, first produce contact-keyed evidence JSON using docs/crm-vnext/mantis-natural-batch-protocol.md.",
        use: "/api/crm-vnext/batch-operating-loop",
        stopCondition: "This is still read-only; resolve evidence or identity queues before any local write approval.",
      },
      {
        step: 22,
        id: "stitch_batch_review",
        action: "Bundle multiple contact clues into one create/enrich/merge/defer review before any card write.",
        use: "/api/crm-vnext/stitch-batch-review",
        stopCondition: "If open evidence questions remain, resolve them before asking for card-write approval.",
      },
      {
        step: 23,
        id: "card_write_approval_packet",
        action: "Prepare explicit human approval packets for items ready to enter a future card-write path.",
        use: "/api/crm-vnext/card-write-approval-packet",
        stopCondition: "This still executes no card mutation; only continue to a write implementation after explicit approval.",
      },
      {
        step: 24,
        id: "card_write_apply",
        action: "Apply explicitly approved items to the local vNext card store with backup and provenance.",
        use: "/api/crm-vnext/card-write-apply",
        stopCondition: "Commit only with approvedBy and explicit selected item(s); never treat this as outbound or merge approval.",
      },
      {
        step: 25,
        id: "engagement_signal_preview",
        action: "Preview supplied engagement signals against stable cards to see scoring deltas and internal review queues.",
        use: "/api/crm-vnext/engagement-signal-preview",
        stopCondition: "Do not contact people, change MailerLite, or write cards from scoring movement alone.",
      },
      {
        step: 26,
        id: "card_merge_review_resolver",
        action: "Resolve explicitly approved staged merge-review items into the local vNext card store.",
        use: "/api/crm-vnext/card-merge-review-resolver",
        stopCondition: "Commit only with approvedBy, explicit review selection, and restricted-service acknowledgement when applicable.",
      },
      {
        step: 27,
        id: "review_fact_identity",
        action: "Review stored facts against local person cards before any rebuild planning.",
        use: "/api/crm-vnext/identity-review",
        stopCondition: "If any fact is unmatched or needs review, ask for identity or business clarification before card mutation.",
      },
      {
        step: 28,
        id: "preview_card_rebuild_diff",
        action: "Preview exact card changes for ready facts without writing them.",
        use: "/api/crm-vnext/card-rebuild-diff",
        stopCondition: "Stop here for sprint closeout unless Alejandro approves a future write policy.",
      },
      {
        step: 29,
        id: "read_daily_brief",
        action: "Read the daily operating picture before drilling into people.",
        use: "/api/crm-vnext/community-daily-brief",
        stopCondition: "If a notify-level queue appears, prepare a decision brief and wait for approval.",
      },
      {
        step: 30,
        id: "inspect_queue_counts",
        action: "Check queue status totals and snapshot deltas.",
        use: "/api/crm-vnext/community-queues",
        stopCondition: "If status is notify, do not send anything; escalate with context.",
      },
      {
        step: 31,
        id: "inspect_focus_queue",
        action: "Open one bounded queue brief for the most relevant operator lane.",
        use: "/api/crm-vnext/community-queue-brief?queueId=<queueId>&limit=<n>",
        stopCondition: "If the queue implies outbound follow-up, draft internally only.",
      },
      {
        step: 32,
        id: "prepare_decision_brief",
        action: "Prepare a no-send decision brief when approval boundaries matter.",
        use: "/api/crm-vnext/community-decision-brief?queueId=<queueId>&limit=<n>",
        stopCondition: "Stop before Telegram, Instagram, email, WhatsApp, ManyChat, or CRM mutation.",
      },
      {
        step: 33,
        id: "inspect_person_card",
        action: "Read exact person context before a human decision note.",
        use: "/api/crm-vnext/person-card?personId=<personId>",
        stopCondition: "Do not treat nextAction as permission to contact the person.",
      },
    ],
    apiEndpoints,
    browserRoutes,
    localCommands,
    guardrails,
    escalationTriggers,
    safety: {
      outboundProhibited: true,
      recordMutationRequiresExplicitApproval: true,
      credentialMutationProhibited: true,
      manyChatLiveMutationProhibited: true,
      instagramPermissionMutationProhibited: true,
      mailerLiteCredentialMutationProhibited: true,
    },
  };
};
